FROM node:16
WORKDIR /yusra-test
COPY package.json ./
COPY package-lock.json ./
RUN npm install
COPY . .
RUN npm run build
EXPOSE 3000
ENTRYPOINT [ "/bin/bash", "-c", "npm run migration:run && npm run start:dev" ]
