
version: 2.1
orbs:
  node: circleci/node@5.0.2

jobs:
  checks:
    executor: node/default
    steps:
      - checkout
      - node/install-packages
      - run:
          name: Linting
          command: npm run lint
      - run:
          name: Unit Tests
          command: npm run test

workflows:
  version: 2
  build:
    jobs:
      - checks